name: Generate Snake Animation

# Runs the workflow every day at midnight UTC
on:
  schedule:
    - cron: "*/5 * * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Generate the snake.svg
      - name: Generate the snake
        uses: Platane/snk@v2
        with:
          github_user_name: Mtp-dev   # Replace with your GitHub username
          outputs: dist/snake.svg

      # Upload the snake.svg to the output branch
      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
